### ISSUE TITLE
Bar and density charts are not matching

### ISSUE THREAD

**Issue by edwahu** [edgemesh/crux.run#7]
At the moment it seems like the two charts for the measures are not matching. For example for Web.dev FCP, August bar chart shows 34% fast, the density chart shows roighly 80% fast:

![image](https://user-images.githubusercontent.com/2666995/65207317-963cce00-dad4-11e9-902d-8333d116b60c.png)

![image](https://user-images.githubusercontent.com/2666995/65207338-a81e7100-dad4-11e9-95ef-46ec2f908101.png)

**Comment by jacobloveless** [comment]
Hi @edwahu !
Yeah this histogram looks off (and I think I know why).
The bar chart (bat charts) look to match the data correctly.
E.g. using web.dev I see (via ChromeUXDashboard)
![image](https://user-images.githubusercontent.com/20774514/65271919-f6327500-dad2-11e9-8bfe-18916a46cfd3.png)
That looks to match Crux.run correctly
![image](https://user-images.githubusercontent.com/20774514/65271962-077b8180-dad3-11e9-95b1-fc23073c9e97.png)

So the root cause here is an optimization in the histogram itself we made on the last push.
Will revert and re-deploy

**Comment by jacobloveless** [comment]
Fixed. And deployed
![image](https://user-images.githubusercontent.com/20774514/65273018-106d5280-dad5-11e9-8dd5-6d9cd3f27b0e.png)
